event: 
  build: event/
  command: python -u event.py
  ports: 
    - "5000:5000"
  links:
    - db
pywhois:
  build: pywhois/
  command: python -u pywhois.py
  ports: 
    - "5001:5001"
  links:
    - db

ipinfo:
  build: ipinfo/
  command: python -u ipinfo.py
  ports:
    - "5002:5002"
  links:
    - db

webclient:
    build: webClient/
    command: python -u webClient.py
    ports:
      - "5003:5003"
    links:
      - event
      - pywhois
      - ipinfo
db: 
  image: mongo:3.0.2
  container_name: mongodb
  volumes:
    - /data/db 
